CREATE DATABASE IF NOT EXISTS smart_queue_system;
USE smart_queue_system;

CREATE TABLE IF NOT EXISTS role (
    role_id INT AUTO_INCREMENT PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    password_hash VARCHAR(255) NOT NULL,
    role_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES role(role_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS sector (
    sector_id INT AUTO_INCREMENT PRIMARY KEY,
    sector_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS location (
    location_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address TEXT,
    sector_id INT NOT NULL,
    FOREIGN KEY (sector_id) REFERENCES sector(sector_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS service (
    service_id INT AUTO_INCREMENT PRIMARY KEY,
    service_name VARCHAR(100) NOT NULL,
    sector_id INT NOT NULL,
    estimated_time_per_token_mins INT DEFAULT 5,
    FOREIGN KEY (sector_id) REFERENCES sector(sector_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS service_counter (
    counter_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    location_id INT NOT NULL,
    service_id INT NOT NULL,
    FOREIGN KEY (location_id) REFERENCES location(location_id) ON DELETE CASCADE,
    FOREIGN KEY (service_id) REFERENCES service(service_id) ON DELETE CASCADE
);

-- which staff is assigned to which counter
CREATE TABLE IF NOT EXISTS staff_counter_assignment (
    assignment_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    counter_id INT NOT NULL,
    status ENUM('ACTIVE', 'INACTIVE') DEFAULT 'ACTIVE',
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (counter_id) REFERENCES service_counter(counter_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS queue (
    queue_id INT AUTO_INCREMENT PRIMARY KEY,
    counter_id INT NOT NULL,
    current_average_wait_time INT DEFAULT 5, /* in minutes */
    status ENUM('ACTIVE', 'CLOSED') DEFAULT 'ACTIVE',
    FOREIGN KEY (counter_id) REFERENCES service_counter(counter_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS token (
    token_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT, /* Can be null if generated by staff offline */
    queue_id INT NOT NULL,
    token_number INT NOT NULL,
    issue_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expected_service_time TIMESTAMP NULL,
    status ENUM('PENDING', 'CALLED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED') DEFAULT 'PENDING',
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL,
    FOREIGN KEY (queue_id) REFERENCES queue(queue_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notification (
    notification_id INT AUTO_INCREMENT PRIMARY KEY,
    token_id INT NOT NULL,
    message TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status ENUM('SENT', 'FAILED', 'PENDING') DEFAULT 'PENDING',
    FOREIGN KEY (token_id) REFERENCES token(token_id) ON DELETE CASCADE
);
